2024-05-23 00:12:39,022 - ERROR - division by zero
2024-05-23 00:17:06,412 - ERROR - {'message': 'division by zero', 'detail': 'Traceback (most recent call last):\n  File "C:\\Users\\Carlos\\Desktop\\Practica Python\\Proyecto Practica Python\\excepciones\\loggins\\GenerarArchivosLogs.py", line 10, in <module>\n    10/ 0\n    ~~^~~\nZeroDivisionError: division by zero\n'}
2024-05-23 00:20:22,262 - ERROR - {'message': 'division by zero', 'detail': 'Traceback (most recent call last):\n  File "C:\\Users\\Carlos\\Desktop\\Practica Python\\Proyecto Practica Python\\excepciones\\loggins\\GenerarArchivosLogs.py", line 19, in <module>\n    10 / 0\n    ~~~^~~\nZeroDivisionError: division by zero\n'}
2024-05-23 00:24:15,675 - ERROR - {'message': 'division by zero', 'detail': 'Traceback (most recent call last):\n  File "C:\\Users\\Carlos\\Desktop\\Practica Python\\Proyecto Practica Python\\excepciones\\loggins\\GenerarArchivosLogs.py", line 20, in <module>\n    10 / 0\n    ~~~^~~\nZeroDivisionError: division by zero\n'}
2024-05-23 00:24:15,676 - ERROR - {'message': 'division by zero', 'detail': 'Traceback (most recent call last):\n  File "C:\\Users\\Carlos\\Desktop\\Practica Python\\Proyecto Practica Python\\excepciones\\loggins\\GenerarArchivosLogs.py", line 28, in write_on_log_file_with_context\n    yield\n  File "C:\\Users\\Carlos\\Desktop\\Practica Python\\Proyecto Practica Python\\excepciones\\loggins\\GenerarArchivosLogs.py", line 38, in <module>\n    var = 10 / 0\n          ~~~^~~\nZeroDivisionError: division by zero\n'}
